on:
  workflow_dispatch:
    inputs:
      model_name:
        required: true
        description: "The name of the Replicate model to publish, e.g `username/modelname`. The model must already exist on Replicate."

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@support-building-cog-from-source
        with:
          cog-commitish: main
          install-cuda: false
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Inpsect the Cog checkout's build.go file
        run: |
          set -x
          cat cog-repo/pkg/docker/build.go
          cat cog-repo/pkg/docker/build.go | grep load
      - name: Build with Cog
        run: |
          set -x
          pwd
          ls -al
          echo $PATH
          cog build

      - name: Push to Replicate
        run: |
          cog push r8.im/${{ inputs.model_name }}
